### ISSUE TITLE
Add references to website

### ISSUE THREAD

**Issue by omonimus1** [Microsoft-Club-SIST/Microsoft-Club-SIST.github.io#1]
To have more redirect from GitHub to the website ([https://microsoft-club-sist.github.io/#](https://microsoft-club-sist.github.io/#) ), I suggest to add a link to the website in the:
* README.md file 
* Website of the repo section (just below the description of the website).

**Comment by KamalDGRT** [comment]
Apologies for the delay.

There have been plans to renovate the site.
So, we will be adding it in `README.md` once it is done.
For now, I am adding the current link in the about section.

Thank you @omonimus1 !
