### ISSUE TITLE
create new branch command

### ISSUE THREAD

**Issue by vikashchander** [Microsoft-Club-SIST/Microsoft-Club-SIST.github.io#2]
###   Create the branch on your local machine and switch in this branch :
```
$ git checkout -b [name_of_new_branch]
```
### Push the branch on github :
```
$ git push origin [name_of new_branch]
```

**Comment by KamalDGRT** [comment]
That is a good suggestion @vikashchander.
Thank you for the same.
We will take that into implementation when the repo re-built.
